language: go
GO111MODULE: on
go:
  - 1.13

git:
  quiet: true

services:
  - docker

before_install:
  - curl -Lo ./kind "https://github.com/kubernetes-sigs/kind/releases/download/v0.6.1/kind-$(uname)-amd64"
  - chmod +x ./kind
  - wget https://github.com/bazelbuild/bazel/releases/download/0.29.1/bazel_0.29.1-linux-x86_64.deb
  # - sha256sum -c tools/bazel_0.3.1-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_0.29.1-linux-x86_64.deb
  - kind create cluster

after_script:
  - kind delete cluster

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
jobs:
  include:
    - stage: test-helm-release
      script: go test tests/rules/release:_spec_test.go -v
