language: go
GO111MODULE: on
go:
  - 1.13

git:
  quiet: true

services:
  - docker

install:
  - ./setup-k8s-tools.sh
  - ./create-k8s-cluster-tiller.sh
  - ./create-k8s-cluster-tillerless.sh
after_script:
  - ./delete-k8s-clusters.sh

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
jobs:
  include:
    - stage: test-helm-v2
      script: kctx kind-bazel-tiller && go test tests/rules/* -v
    - stage: test-helm-v3
      script: kctx kind-bazel-tillerless && go test test/rules/* -v
