steps:
# - name: "gcr.io/mm-opensource-cloudbuild/bazel-rules-testing-environment"
#   id: "setup"
#   entrypoint: /bin/bash
#   args: ["./tests/k8s-setup.sh", "&&", "kubectx kind-bazel-tillerless"]
- name: "istionightly/kind:latest"
  id: "k8s"
  entrypoint: /bin/bash
  args: ["create", "cluster", "--name", "bazel-rules"]
- name: "gcr.io/mm-opensource-cloudbuild/bazel-rules-testing-environment"
  id: "tests"
  entrypoint: /bin/bash
  waitFor:
  - "k8s"
  args: ["go", "test", "tests/rules/*", "-v"]