name: Kind
on: [pull_request]
jobs:
  test-unit:
    name: Create a Kind cluster
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Install latest version of Kind
      run: |
        GO111MODULE=on go get sigs.k8s.io/kind
    - name: Create Kind cluster
      run: |
        PATH=$(go env GOPATH)/bin:$PATH kind create cluster --name bazel-rules
    - name: Import gpg
      run: |
        gpg --import ./tests/resources/pgp/sops_test_key.asc
    - name: Setup Bazel
      uses: abhinavsingh/setup-bazel@v3
      with:
        version: 4.1.0
    - name: Run integration tests
      run: |
        go test tests/rules/* -v
